# Generated by Django 3.0.5 on 2020-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200424_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunittype',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='description'),
        ),
    ]
