# Generated by Django 3.0.5 on 2020-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_storageunittype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunittype',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
    ]
