# Generated by Django 3.0.5 on 2020-04-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200425_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handlingunit',
            options={'verbose_name': 'handling unit', 'verbose_name_plural': 'handling units'},
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='title',
        ),
    ]
