# Generated by Django 3.0.5 on 2020-04-25 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200425_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='units_quantity',
        ),
        migrations.AddField(
            model_name='delivery',
            name='units',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='units quantity'),
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handlingunit',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_units', to='web.Delivery'),
        ),
    ]
