# Generated by Django 3.0.5 on 2020-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200425_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='units',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='serial number'),
        ),
    ]
