# Generated by Django 3.0.5 on 2020-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='country',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='handling_unit',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='material',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='handlingunit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
        migrations.RemoveField(
            model_name='materialtype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='storageunittype',
            name='creator',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='HandlingUnit',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.DeleteModel(
            name='StorageUnitType',
        ),
    ]
